### PR TITLE
Python 3 compatibility for pdb2pqr

### PR DESCRIPTION
**Pull request by speleo3**
Tested with Python 2.7, 3.6, 3.7 by running **pdb2pqr** with various parameters (including `--apbs-input` and `--with-ph`).

Based on @tonigi's first commit from PR #440, but excludes his additional changes like propka3.1 support (could be easily added in a separate PR).

This PR only covers **pdb2pqr** so far. I can send a separate PR for **pdb2pka** once this is merged.

### CODE REVIEW

**Comment by speleo3** [comment]
For the record: This doesn't touch the **SCons** build system, it simply runs pdb2pqr from the source directory.

**Comment by sobolevnrm** [comment]
Wow -- thank you very much for doing this!

**Comment by cowsandmilk** [comment]
Are you missing changes to pdb2pqr.py.in ? That is, you might have modified pdb2pqr.py in your copy and not made the change to pdb2pqr.py.in for the fact that has_key has been removed.

**Comment by speleo3** [comment]
You are right @cowsandmilk. I didn't notice because I'm not using the SCons build system.

**Comment by speleo3** [comment]
@sobolevnrm do you have plans to merge this? Or should we use a fork like https://github.com/tonigi/apbs-pdb2pqr/tree/htmd-fixups/ instead?

**Comment by sobolevnrm** [comment]
Yes, we are planning to merge this.  We are very short-staffed right now.
Please do not fork the code.

Thank you,

Nathan

**Pull request merged**
