### PR TITLE
Python 3 compatibility and propka3.1 support

### PR DESCRIPTION
**Pull request by tonigi**
Plus minor changes. Needs testing.

### CODE REVIEW

**Comment by tonigi** [comment]
Travis failures seem unrelated (cc1plus: error: unrecognized command line option ‘-std=c++11’)

**Comment by keith923** [comment]
Travis is only testing APBS.

**Comment by keith923** [comment]
I tried the following:
```
> python3 scons/scons.py 
  File "scons/scons.py", line 194
    print "  %s" % path
               ^
SyntaxError: Missing parentheses in call to 'print'
```
The installation process is still not Python 3 compatible.  Since SCons is also responsible for running the tests, I can only assume that the changes have not been tested.

**Comment by kmonson** [comment]
I was maintaining a local copy of scons (scons provides packages to make this simple) and they have updated since the last time I’ve updated the copy in the repo.

It looks like the latest version of scons (2.5.0 released in April) drops support for 2.6 but does not yet provide 3 support. I think pdb2pqr uses 2.4.1 or 2.4.0.

**Comment by keith923** [comment]
Thanks for that info Kyle.  So if we want to support Python 3, it looks like we'd need something other than SCons.  Dang.

**Comment by tonigi** [comment]
The tests can be run manually, but fail under py3 because of randomized dictionaries - https://github.com/Electrostatics/apbs-pdb2pqr/issues/439

**Comment by keith923** [comment]
Even so, I don't see how we can update to Python 3 until we have a replacement for SCons.

**Pull request merged**
